package testclient

const (

	// Data below is not standard deployment json and service json, it's yce's deployment and service

	CHECK_TEMPLATE = `{"name":"nginx-template"}`
	//CREATE_TEMPLATE = `{"name":"nginx-template","deployment":{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"name":"nginx-template"}},"service":{"apiVersion":"v1","kind":"Service","metadata":{"name":"nginx-svc-template"}}}`
	//CREATE_TEMPLATE = `{"name":"nginx-template", "deployment":{}, "service":{}}`
	//CREATE_TEMPLATE = `{"name":"nginx-template"}`
	//CREATE_TEMPLATE = `{\"name\": \"test1\",\"deployment\": {\"dcIdList\": [1],\"deployment\": {\"metadata\": {\"name\": \"xuxueyan1\",\"namespace\": \"dev\",\"labels\": {\"name\": \"xuxueyan1\",\"author\": \"xueyan.xu\",\"version\": \"\"}},\"spec\": {\"template\": {\"spec\": {\"containers\": [{\"env\": [{\"name\": \"DB_USER\",\"value\": \"vv\"},{\"name\": \"DB_PASS\",\"value\": \"vvv\"}],\"image\": \"\",\"resources\": {\"limits\": {\"cpu\": \"1000m\",\"memory\": \"2000M\"}},\"ports\": [{\"protocol\": \"TCP\",\"name\": \"port1\",\"containerPort\": 2234}],\"name\": \"xuxueyan1\"}]},\"metadata\": {\"labels\": {\"name\": \"xuxueyan1\",\"author\": \"xueyan.xu\",\"version\": \"\"}}},\"replicas\": 1}},\"orgName\": \"dev\",\"appName\": \"xuxueyan1\"},\"service\": {\"serviceName\": \"ex1\",\"orgName\": \"dev\",\"dcIdList\": [1],\"service\": {\"kind\": \"Service\",\"apiVersion\": \"v1\",\"metadata\": {\"name\": \"ex1\",\"labels\": {\"name\": \"ex1\",\"namespace\": \"dev\",\"author\": \"xueyan.xu\",\"type\": \"service\"}},\"spec\": {\"type\": \"NodePort\",\"selector\": {\"name\": \"vv\"},\"ports\": [{\"name\": \"port\",\"protocol\": \"\",\"port\": \"10000\",\"targetPort\": \"10000\",\"nodePort\": \"32761\"}]}}}}`
	CREATE_TEMPLATE = `{"name": "test1","deployment": {"dcIdList": [1],"deployment": {"metadata": {"name": "xuxueyan1","namespace": "dev","labels": {"name": "xuxueyan1","author": "xueyan.xu","version": ""}},"spec": {"template": {"spec": {"containers": [{"env": [{"name": "DB_USER","value": "vv"},{"name": "DB_PASS","value": "vvv"}],"image": "","resources": {"limits": {"cpu": "1000m","memory": "2000M"}},"ports": [{"protocol": "TCP","name": "port1","containerPort": 2234}],"name": "xuxueyan1"}]},"metadata": {"labels": {"name": "xuxueyan1","author": "xueyan.xu","version": ""}}},"replicas": 1}},"orgName": "dev","appName": "xuxueyan1"},"service": {"serviceName": "ex1","orgName": "dev","dcIdList": [1],"service": {"kind": "Service","apiVersion": "v1","metadata": {"name": "ex1","labels": {"name": "ex1","namespace": "dev","author": "xueyan.xu","type": "service"}},"spec": {"type": "NodePort","selector": {"name": "vv"},"ports": [{"name": "port","protocol": "","port": 10000,"targetPort": 10000,"nodePort": 32761}]}}}}`
	//CREATE_TEMPLATE_ONLY_DEPLOYMENT = `{"name":"test1", "deployment": {"dcIdList": [1],"deployment": {"metadata": {"name": "xuxueyan1","namespace": "dev","labels": {"name": "xuxueyan1","author": "xueyan.xu","version": ""}},"spec": {"template": {"spec": {"containers": [{"env": [{"name": "DB_USER","value": "vv"},{"name": "DB_PASS","value": "vvv"}],"image": "","resources": {"limits": {"cpu": "1000m","memory": "2000M"}},"ports": [{"protocol": "TCP","name": "port1","containerPort": 2234}],"name": "xuxueyan1"}]},"metadata": {"labels": {"name": "xuxueyan1","author": "xueyan.xu","version": ""}}},"replicas": 1}},"orgName": "dev","appName": "xuxueyan1"}}`
	//CREATE_TEMPLATE_ONLY_SERVICE = `{"name":"test1", "service": {"serviceName": "ex1","orgName": "dev","dcIdList": [1],"service": {"kind": "Service","apiVersion": "v1","metadata": {"name": "ex1","labels": {"name": "ex1","namespace": "dev","author": "xueyan.xu","type": "service"}},"spec": {"type": "NodePort","selector": {"name": "vv"},"ports": [{"name": "port","protocol": "","port": 10000,"targetPort": 10000,"nodePort": 32761}]}}}}`
	DELETE_TEMPLATE = `{"name":"nginx-template","id":7}`
	UPDATE_TEMPLATE = `{"name":"nginx-template","deployment":{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"name":"nginx-template","namespace":"test-template"}},"service":{"apiVersion":"v1","kind":"Service","metadata":{"name":"nginx-svc-template", "namespace":"test-template"}}}`

)
